/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DepthUpdate {
  s: string
  bb: number
  bq: number
  ba: number
  aq: number
}
export interface TradeUpdate {
  s: string
  p: number
  q: number
  t: number
  ts: number
  m: boolean
}
export declare class DeltaNativeClient {
  constructor(apiKey: string, apiSecret: string, baseUrl?: string | undefined | null)
  placeOrder(body: any): Promise<any>
  getWalletBalance(): Promise<any>
  getPositions(): Promise<any>
}
export declare class BinanceListener {
  constructor()
  start(assets: Array<string>, callback: (err: Error | null, arg: DepthUpdate) => any): void
}
export declare class BinanceTradeListener {
  constructor()
  start(assets: Array<string>, callback: (err: Error | null, arg: TradeUpdate) => any): void
}
